backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow # Uncomment to activate editorial workflow

media_folder: "static/uploads" # Media files will be stored in the repo under static/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

logo_url: https://k6mtv.broadsky.net/ares-logo.svg

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    description: "News items to be published on the site"
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, hint: "Flip right = set draft mode (won't be shown on website)"}
      - {label: "Summary", name: "summary", widget: "text", hint: "Optional summary shown in list views (will be auto-generated if blank)"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "silent-keys" # Used in routes, e.g., /admin/collections/blog
    label: "Silent Keys" # Used in the UI
    description: "Rememberances of Silent Keys"
    folder: "content/silent-keys" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, hint: "Flip right = set draft mode (won't be shown on website)"}
      - {label: "Summary", name: "summary", widget: "text", hint: "Optional summary shown in list views (will be auto-generated if blank)"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "data"
    label: "Data Files"
    create: false
    delete: false
    files:
      - label: "Calendar Events"
        description: "Events to be listed on the site's calendar page"
        folder: "data" # The path to the folder where the documents are stored
        name: "calendar"
        file: "data/calendar.yaml"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Type", name: "type", widget: "string", hint: "Must be 'city', 'county', 'cert', 'react', or blank (other)"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Time", name: "time", widget: "string", hint: "Must be in HHMM-HHMM form"}
          - {label: "Link", name: "link", widget: "string", hint: "Optional; if present must be a valid URL for the event (e.g. 'https://...'"}
          - {label: "Update", name: "update", widget: "string", hint: "Optional update (e.g. 'CANCELLED')"}
      - label: "Staff"
        name: "people"
        file: "data/people.yaml"
        fields:
          - {label: "Call", name: "call", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Photo", name: "photo", widget: "image"}

